apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "customer-managed-agent.fullname" . }}-agent-config
  labels:
  {{- include "customer-managed-agent.labels" . | nindent 4 }}
data:
  PULUMI_AGENT_IMAGE: {{ .Values.agentConfig.pulumiAgentImage | quote }}
  PULUMI_AGENT_IMAGE_PULL_POLICY: {{ .Values.agentConfig.pulumiAgentImagePullPolicy
    | quote }}
  PULUMI_AGENT_SERVICE_URL: {{ .Values.agentConfig.pulumiAgentServiceUrl | quote
    }}
