apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "customer-managed-agent.fullname" . }}-deployment-agent-pool
  labels:
  {{- include "customer-managed-agent.labels" . | nindent 4 }}
  annotations:
    app.kubernetes.io/name: pulumi-deployment-agent-pool
spec:
  replicas: {{ .Values.deploymentAgentPool.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: customer-managed-deployment-agent
    {{- include "customer-managed-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: customer-managed-deployment-agent
      {{- include "customer-managed-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PULUMI_AGENT_DEPLOY_TARGET
          value: {{ quote .Values.deploymentAgentPool.agent.env.pulumiAgentDeployTarget
            }}
        - name: PULUMI_AGENT_SHARED_VOLUME_DIRECTORY
          value: {{ quote .Values.deploymentAgentPool.agent.env.pulumiAgentSharedVolumeDirectory
            }}
        - name: PULUMI_AGENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              key: PULUMI_AGENT_SERVICE_URL
              name: {{ include "customer-managed-agent.fullname" . }}-agent-config
        - name: PULUMI_AGENT_IMAGE
          valueFrom:
            configMapKeyRef:
              key: PULUMI_AGENT_IMAGE
              name: {{ include "customer-managed-agent.fullname" . }}-agent-config
        - name: PULUMI_AGENT_IMAGE_PULL_POLICY
          valueFrom:
            configMapKeyRef:
              key: PULUMI_AGENT_IMAGE_PULL_POLICY
              name: {{ include "customer-managed-agent.fullname" . }}-agent-config
        - name: PULUMI_AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              key: PULUMI_AGENT_TOKEN
              name: {{ include "customer-managed-agent.fullname" . }}-agent-secret
        - name: PULUMI_AGENT_SERVICE_ACCOUNT_NAME
          value: {{ quote .Values.deploymentAgentPool.agent.env.pulumiAgentServiceAccountName
            }}
        - name: PULUMI_AGENT_NUM_CPUS
          value: {{ quote .Values.deploymentAgentPool.agent.env.pulumiAgentNumCpus }}
        - name: PULUMI_AGENT_MEM_QUANTITY
          value: {{ quote .Values.deploymentAgentPool.agent.env.pulumiAgentMemQuantity
            }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.deploymentAgentPool.agent.image.repository }}:{{ .Values.deploymentAgentPool.agent.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deploymentAgentPool.agent.imagePullPolicy }}
        name: agent
        resources: {}
        volumeMounts:
        - mountPath: /mnt/work
          name: agent-work
      serviceAccountName: {{ include "customer-managed-agent.fullname" . }}-deployment-agent
      volumes:
      - emptyDir: {}
        name: agent-work
      - configMap:
          name: {{ include "customer-managed-agent.fullname" . }}-agent-config
        name: agent-config
