apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "customer-managed-agent.fullname" . }}-deployment-agent
  labels:
  {{- include "customer-managed-agent.labels" . | nindent 4 }}
  annotations:
    pulumi.com/autonamed: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "customer-managed-agent.fullname" . }}-deployment-agent'
subjects:
- kind: ServiceAccount
  name: '{{ include "customer-managed-agent.fullname" . }}-deployment-agent'
  namespace: '{{ .Release.Namespace }}'
