apiVersion: v1
kind: Secret
metadata:
  name: {{ include "customer-managed-agent.fullname" . }}-agent-secret
  labels:
  {{- include "customer-managed-agent.labels" . | nindent 4 }}
data:
  PULUMI_AGENT_TOKEN: {{ required "agentSecret.pulumiAgentToken is required" .Values.agentSecret.pulumiAgentToken
    | b64enc | quote }}
