apiVersion: v1
kind: Pod
metadata:
  labels:
    env: development
spec:
  containers:
    - name: pulumi-workflow
      env:
        - name: NEW_VARIABLE
          value: "some_value"
      volumeMounts:
        - name: my-empty-dir 
          mountPath: "/app/data" 
  volumes:
    - name: my-empty-dir
      emptyDir: {}