agentConfig:
  pulumiAgentImage: pulumi/customer-managed-deployment-agent:latest-amd64
  pulumiAgentImagePullPolicy: Always
  pulumiAgentServiceUrl: https://api.pulumi.com
agentSecret:
  pulumiAgentToken: ""
deploymentAgent:
  serviceAccount:
    annotations:
      pulumi.com/autonamed: "true"
kubernetesClusterDomain: cluster.local
pool:
  agent:
    env:
      pulumiAgentDeployTarget: kubernetes
      pulumiAgentMemQuantity: ""
      pulumiAgentNumCpus: ""
      pulumiAgentServiceAccountName: deployment-agent
      pulumiAgentSharedVolumeDirectory: /mnt/work
    image:
      repository: pulumi/customer-managed-deployment-agent
      tag: latest-amd64
    imagePullPolicy: Always
  replicas: 3
