# -- Specifies the strategy used to replace old Pods by new ones, default: `RollingUpdate`
deploymentStrategy: ""

# -- Specifies the replica count for the deployment
replicaCount: 1

# -- Specifies termination grace period, default: `300`
terminationGracePeriodSeconds: 300

# -- Provide a name in place of pulumi-kubernetes-operator
nameOverride: ""
# -- String to fully override "pulumi-kubernetes-operator.fullname"
fullnameOverride: ""

customerManagedAgentConfig:
  backEndApiUrl: https://api.pulumi.com
  agentDeployTarget: kubernetes
  accessTokenSecretName: ""

image:
  # -- The image registry to pull from
  registry: docker.io
  # -- The image repository to pull from
  repository: pulumi/customer-managed-deployment-agent
  # -- The image pull policy
  pullPolicy: IfNotPresent
  # -- The image tag to pull, default: `latest-amd64`
  tag: "latest-amd64"

# -- The image pull secrets
imagePullSecrets: ""

# RBAC settings
rbac:
  # -- Specifies whether RBAC resources should be created
  create: true
  # -- Specifies whether namespaced roles and bindings should be created
  createRole: false
  # -- Specifies extra rules for the role
  extraRules: []

serviceAccount:
  # Specifies whether a service account should be created
  # -- Create service account
  create: true
  # Annotations to add to the service account
  # -- Additional ServiceAccount annotations
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # -- Service account name to use, when empty will be set to created account if
  name: ""

# -- Labels to add to the customer-managed-deployment-agent pod. default: {}
podLabels: {}

# -- Pod annotations
podAnnotations: {}

# -- Deployment annotations
deploymentAnnotations: {}

# -- You can configure extra sidecar containers to run within the customer-managed-deployment-agent pod. default: []
extraSidecars: []
#  - name: sidecar-example
#    image: busybox
#    command: ["/bin/sh", "-c", "echo hello from sidecar"]

# -- Security Context see [values.yaml](values.yaml)
securityContext:
  allowPrivilegeEscalation: false
  # readOnlyRootFilesystem: true
  # seccompProfile:
  #   type: RuntimeDefault
  capabilities:
    drop:
      - ALL

# -- CPU/Memory resource requests/limits
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi

# -- You can configure extra init containers to run within the pulumi-kubernetes-operator pod. default: []
initContainers: []

# -- Node selector
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []