name: ct-linting-and-testing
on:
  pull_request:
    paths:
      - helm/**
      - "!helm/customer-managed-agent/README.md"
      - "!helm/customer-managed-agent/README.md.gotmpl"

env:
  VERSION: latest-amd64

permissions:
  id-token: write
  contents: read

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.6.3

      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.11

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ${{ github.workspace }}/.github/configs/ct-lint-install.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_charts=$charts" >> "$GITHUB_OUTPUT"
          fi

      - name: Run Artifact Hub lint
        run: |
          curl -s https://api.github.com/repos/artifacthub/hub/releases/latest | grep -E 'browser_download_url' | grep linux_amd64.tar.gz\" | grep -Eo 'https://[^\"]*' | xargs wget -O - | tar -xz
          ./ah lint -p helm/ || exit 1
          rm -f ./ah

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ${{ github.workspace }}/.github/configs/ct-lint-install.yaml --lint-conf ${{ github.workspace }}/.github/configs/lintconf.yaml

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.10.0
        if: steps.list-changed.outputs.changed == 'true'
      
      - name: Pull docker image
        run: |
          docker pull pulumi/customer-managed-deployment-agent:${{ env.VERSION }}
      
      - name: Load images into KinD
        run: |
          kind load docker-image pulumi/customer-managed-deployment-agent:${{ env.VERSION }} --name chart-testing

      - name: Run chart-testing (install)
        run: ct install --config ${{ github.workspace }}/.github/configs/ct-lint-install.yaml  --helm-extra-set-args "--set=image.tag=${{ env.VERSION }}"