name: Publish

on:
  workflow_call:
    inputs:
      goreleaser-args:
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'
      - name: Check Cosign install
        run: cosign version
      - name: Set BUILD_STAMP
        run: |
          echo "BUILD_STAMP=$(cd ./pulumi-service && date -u '+%Y-%m-%d_%I:%M:%S%p')" >> $GITHUB_ENV
      - name: Set BUILD_GIT_HASH
        run: |
          echo "BUILD_GIT_HASH=$(cd ./pulumi-service && git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Login to Docker Hub as pulumi-bot
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: ${{ inputs.goreleaser-args }}
          version: latest
